# Adaptador 'async' gera problemas na sincronização dos sockets, se mais que um computador/aparelho abrir conexão websocket
# para ter mais precisão, usar:
  # adapter: redis
  # url: 'redis://localhost:6379/1'

development:
  adapter: redis
  url: 'redis://localhost:6379/1'

test:
  adapter: async

production:
  adapter: redis
  url: "<%= ENV['REDISTOGO_URL'] %>"
