<% if ENV['HEROKU_ENV'].present? %>

async: &async
  adapter: async

development: *async
test: *async
production: *async

<% else %>

redis: &redis
  adapter: redis
  url: redis://localhost:6379

development: *redis
test: *redis
production: *redis

<% end %>
