default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  template: template0

development:
  <<: *default
  database: votweb_development

test:
  <<: *default
  database: votweb_test
  min_messages: WARNING

<% if ENV['HEROKU_ENV'].present? %>
production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: utf8
  pool: 20
  min_messages: WARNING
<% else %>
production:
  database: votweb
  pool: 20
  username: postgres
  host: db
  template: template0
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
<% end %>
