default_actions: &default_actions
  - read
  - create
  - update
  - destroy

Administrator:
  - read
  - create
  - update
  - unlock
  - destroy

Role: *default_actions
Councillor: *default_actions
Party: *default_actions
Surrogate: *default_actions
Project: *default_actions
PlenarySession: *default_actions
Hold: *default_actions
