default_actions: &default_actions
  - read
  - create
  - update
  - destroy

Role: *default_actions
Councillor: *default_actions
Party: *default_actions
SessionItem: *default_actions

Administrator:
  - read
  - create
  - update
  - unlock
  - destroy

PlenarySession:
  - read
  - create
  - update
  - manage_session
  - destroy
