default_actions: &default_actions
  - read
  - create
  - update
  - destroy

Administrator:
  - read
  - create
  - update
  - unlock
  - destroy

Role: *default_actions
Alderman: *default_actions
Party: *default_actions
